Fixed the SegFault when :func:`PyEval_SetTrace` is used with no Python frame on stack.
